### ISSUE TITLE
info for using this with ccs811 and bme280 fromsparkfun

### ISSUE THREAD

**Issue by Giaitzoglou** [akkerman/espthp#1]
hi i know that this question is not for here but i have been using your library for six months now for my bme280 sensor with no problem now i want to upgrade it to the ccs811 + bme280 sensor from sparkfun is there a way to use your mqtt library and the sparkfuns library to send by mqtt all the values ?
all help will be appreciated cause i am not good at coding for mqtt
thanks in advance 
chris giaitzoglou

**Comment by Giaitzoglou** [comment]
Hi please delete this I miss post it to a different git

**Comment by akkerman** [comment]
Closed.
Question was mis posted.
